from setuptools import setup, find_packages

setup(
    name="f5_tts",
    version="0.1.0",
    author="svp19",
    author_email="svp19",
    description="INF5: A Speech Processing Model",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/svp19/inf5",
    packages=find_packages(include=["f5_tts", "f5_tts.*"]),
    install_requires=[
        "accelerate>=0.33.0",
        "cached_path",
        "click",
        "datasets",
        "ema_pytorch>=0.5.2",
        "hydra-core>=1.3.0",
        "jieba",
        "librosa",
        "matplotlib",
        "numpy<=1.26.4",
        "pydub",
        "pypinyin",
        "safetensors",
        "soundfile",
        "tomli",
        "torch>=2.0.0",
        "torchaudio>=2.0.0",
        "torchdiffeq",
        "tqdm>=4.65.0",
        "transformers",
        "transformers_stream_generator",
        "vocos",
        "wandb",
        "x_transformers>=1.31.14",
    ],
    dependency_links=[
        "git+https://github.com/svp19/INF5.git"
    ],
    python_requires=">=3.7",
)
